# Generated by Django 3.2.7 on 2021-12-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_shippingfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingfee',
            name='city',
            field=models.CharField(default='Mushin', max_length=50),
        ),
    ]
