# Generated by Django 3.2.7 on 2021-12-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_shippingfee_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='delfee',
            name='fee21',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='fee22',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='fee23',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='fee24',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='fee25',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='fee26',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='fee27',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='fee28',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='fee29',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='fee30',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='fee31',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='fee32',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='fee33',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='fee34',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='fee35',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='fee36',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='fee37',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc21',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc22',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc23',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc24',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc25',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc26',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc27',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc28',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc29',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc30',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc31',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc32',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc33',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc34',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc35',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc36',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc37',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
