# Generated by Django 3.2.7 on 2021-12-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20211229_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='delfee',
            name='fee38',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delfee',
            name='loc38',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
