# Generated by Django 3.2.7 on 2021-09-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to='uploads/')),
                ('phone_one', models.CharField(max_length=14)),
                ('phone_two', models.CharField(max_length=14)),
                ('location', models.CharField(max_length=200)),
                ('insta', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'setting',
            },
        ),
    ]
