# Generated by Django 3.2.7 on 2021-12-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='bannerimg',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
