# Generated by Django 3.2.7 on 2021-12-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_setting_bannerimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='bannerimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
