# Generated by Django 3.2.7 on 2021-10-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_billinginfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingInfo',
        ),
    ]
