# Generated by Django 3.2.7 on 2021-10-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_billinginfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billinginfo',
            options={'managed': True, 'verbose_name': 'billinginfo', 'verbose_name_plural': 'billinginfo'},
        ),
        migrations.AlterModelTable(
            name='billinginfo',
            table='billinginfo',
        ),
    ]
