# Generated by Django 3.2.7 on 2021-09-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
