# Generated by Django 3.2.7 on 2021-10-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, editable=False, max_length=70, null=True),
        ),
    ]
