# Generated by Django 3.2.7 on 2021-10-14 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210930_0032'),
        ('order', '0004_order_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customproduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.customproduct'),
        ),
    ]
