# Generated by Django 3.2.7 on 2021-10-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_cart_customproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customproduct',
        ),
    ]
