# Generated by Django 3.2.7 on 2021-12-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20211223_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('Ikeja', 'Ikeja'), ('Yaba', 'Yaba'), ('Oshodi', 'Oshodi'), ('Egbeda', 'Egbeda'), ('Surulere', 'Surulere'), ('Ikotun', 'Ikotun'), ('Ketu', 'Ketu'), ('Mile 12', 'Mile 12'), ('Mile 2', 'Mile 2'), ('Festac', 'Festac'), ('Okokomaiko', 'Okokomaiko'), ('Lekki', 'Lekki'), ('Ibeju Lekki', 'Ibeju Lekki'), ('Aja', 'Aja'), ('Ogba', 'Ogba'), ('Costain', 'Costain'), ('Ogudu', 'Ogudu'), ('Magodo Phase 1', 'Magodo Phase 1'), ('Magodo Phase 2', 'Magodo Phase 2'), ('Bariga', 'Bariga'), ('Victoria Island', 'Victoria Island'), ('Iyana Ipaja', 'Iyana Ipaja'), ('Agege', 'Agege'), ('Gbagada', 'Gbagada'), ('Omole', 'Omole'), ('Mushin', 'Mushin'), ('Abule Egba', 'Abule Egba'), ('Iyana Oworo', 'Iyana Oworo'), ('Bergar', 'Bergar'), ('Satellite Town', 'Satellite Town'), ('Sangotedo', 'Sangotedo'), ('Ebute Meta', 'Ebute Meta'), ('Ikota', 'Ikota'), ('Fagba', 'Fagba'), ('Pangroove', 'Pangroove'), ('Onipanu', 'Onipanu'), ('Outside Lagos', 'Outside Lagos'), ('Ikorodu', 'Ikorodu')], max_length=30),
        ),
    ]
