# Generated by Django 3.2.7 on 2021-12-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20211224_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
