# Generated by Django 3.2.7 on 2021-12-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_orderplaced_payment_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(default='displayed color', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.TextField(default='displayed size'),
        ),
    ]
