# Generated by Django 3.2.7 on 2021-12-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20211225_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Preparing', 'Preparing'), ('Onshipping', 'Onshipping'), ('Delivered', 'Delivered')], default='New', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Preparing', 'Preparing'), ('Onshipping', 'Onshipping'), ('Delivered', 'Delivered')], default='New', max_length=30),
        ),
    ]
