# Generated by Django 3.2.7 on 2021-09-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerange',
            name='price_range',
            field=models.CharField(max_length=20),
        ),
    ]
