# Generated by Django 3.2.7 on 2021-09-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210925_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_list',
            field=models.BooleanField(default=False),
        ),
    ]
