# Generated by Django 3.2.7 on 2021-09-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_cat_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner_four',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='banner_three',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='banner_two',
            field=models.BooleanField(default=False),
        ),
    ]
