# Generated by Django 3.2.7 on 2021-09-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210925_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='banner_four',
            new_name='adire',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='banner_three',
            new_name='bags',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='banner_two',
            new_name='urban_wear',
        ),
    ]
