# Generated by Django 3.2.7 on 2021-09-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
