# Generated by Django 3.2.7 on 2021-09-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_bulk_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_list',
            new_name='clist',
        ),
    ]
