# Generated by Django 3.2.7 on 2021-09-27 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_mcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mcat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.mcategory'),
        ),
    ]
