# Generated by Django 3.2.7 on 2021-09-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_mcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcategory',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
