# Generated by Django 3.2.7 on 2021-09-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=models.BooleanField(default=False),
        ),
    ]
