# Generated by Django 3.2.7 on 2021-09-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_mcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
