# Generated by Django 3.2.7 on 2021-09-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_customimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.mcategory'),
        ),
    ]
