# Generated by Django 3.2.7 on 2021-09-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_mcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('price', models.PositiveIntegerField()),
                ('bulk_price', models.PositiveIntegerField(default=0)),
                ('dis_price', models.PositiveIntegerField()),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('colors', models.CharField(max_length=1000)),
                ('sizes', models.CharField(max_length=1000)),
                ('availability', models.CharField(choices=[('In stock', 'In stock'), ('Out of stock', 'Out of stock')], max_length=20)),
                ('product_code', models.CharField(default='none', max_length=10000)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('banner', models.BooleanField(default=False)),
                ('adire', models.BooleanField(default=False)),
                ('urban_wear', models.BooleanField(default=False)),
                ('bags', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.category')),
                ('mcat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.mcategory')),
                ('prange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.pricerange')),
            ],
            options={
                'verbose_name': 'customproduct',
                'verbose_name_plural': 'customproduct',
                'db_table': 'customproduct',
                'managed': True,
            },
        ),
    ]
