# Generated by Django 3.2.7 on 2021-10-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_cart_customproduct'),
        ('products', '0022_auto_20210930_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.CharField(choices=[('main', 'main'), ('custom', 'custom')], default='main', max_length=6),
        ),
        migrations.DeleteModel(
            name='CustomProduct',
        ),
    ]
