# Generated by Django 3.2.7 on 2021-12-24 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20211223_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loveit',
            name='user',
        ),
    ]
